name: "Sync GitHub Labels"

on:
  push:
    paths:
      - .github/labels/issue-label.yml
      - .github/workflows/sync-issue-labels.yaml

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync labels from config
        uses: crazy-max/ghaction-github-labeler@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/ISSUE_TEMPLATE/issue-label.yml
